// <auto-generated />
using System;
using IoTDevice.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IoTDevice.Migrations
{
    [DbContext(typeof(IoTDeviceDBContext))]
    [Migration("20220509034815_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24");

            modelBuilder.Entity("IoTDevice.Entities.Device", b =>
                {
                    b.Property<int>("SerialNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DeviceStartTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasOutsideTemperature")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOperational")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MachineIsBroken")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SilentMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("SerialNumber");

                    b.ToTable("Device");
                });
#pragma warning restore 612, 618
        }
    }
}
